cmake_minimum_required(VERSION 3.20)

if(NOT license_output OR NOT tutorial_source)
  message(FATAL_ERROR "license_output and tutorial_source are required")
endif()
file(MAKE_DIRECTORY "${license_output}")
file(LOCK "${license_output}/.stage.lock" GUARD PROCESS TIMEOUT 120)
file(REMOVE_RECURSE "${license_output}/tutorial" "${license_output}/aria")
file(MAKE_DIRECTORY "${license_output}/tutorial" "${license_output}/aria")
foreach(document LICENSE THIRD_PARTY_NOTICES.md)
  configure_file("${tutorial_source}/${document}" "${license_output}/tutorial/${document}" COPYONLY)
endforeach()
if(aria_source)
  foreach(document LICENSE THIRD_PARTY_NOTICES.md)
    if(EXISTS "${aria_source}/${document}")
      configure_file("${aria_source}/${document}" "${license_output}/aria/${document}" COPYONLY)
    else()
      message(WARNING "Selected Aria source lacks ${document}; obtain matching materials before distribution")
    endif()
  endforeach()
  if(http_enabled)
    set(components json mira)
    if(http_tls)
      list(APPEND components openssl)
    endif()
    foreach(component IN LISTS components)
      set(source "${${component}_source}")
      if(component STREQUAL "json")
        set(license LICENSE.MIT)
      elseif(component STREQUAL "openssl")
        set(license LICENSE.txt)
      else()
        set(license LICENSE)
      endif()
      if(NOT source OR NOT EXISTS "${source}/${license}")
        message(WARNING "Selected ${component} has no known source license; supply matching materials before distribution")
        continue()
      endif()
      set(destination "${license_output}/aria/${component}")
      configure_file("${source}/${license}" "${destination}/${license}" COPYONLY)
      file(GLOB notices "${source}/NOTICE*" "${source}/THIRD_PARTY_NOTICES*")
      foreach(notice IN LISTS notices)
        if(NOT IS_DIRECTORY "${notice}")
          file(COPY "${notice}" DESTINATION "${destination}")
        endif()
      endforeach()
      if(component STREQUAL "json")
        file(GLOB_RECURSE headers "${source}/include/nlohmann/*.hpp")
        set(attributions "")
        foreach(header IN LISTS headers)
          file(STRINGS "${header}" lines ENCODING UTF-8
            REGEX "SPDX-(FileCopyrightText|License-Identifier):")
          list(APPEND attributions ${lines})
        endforeach()
        list(REMOVE_DUPLICATES attributions)
        list(SORT attributions)
        string(JOIN "\n" attributions ${attributions})
        file(WRITE "${destination}/ATTRIBUTIONS.txt" "${attributions}\n")
      endif()
    endforeach()
  endif()
elseif(aria_sdk_licenses AND IS_DIRECTORY "${aria_sdk_licenses}")
  file(COPY "${aria_sdk_licenses}/" DESTINATION "${license_output}/aria")
else()
  message(WARNING "Selected Aria SDK does not expose license materials; obtain them from its distributor before redistribution")
endif()
